### ISSUE TITLE
TX State data source

### ISSUE THREAD

**Issue by umbernhard** [openelections/openelections-sources-tx#2]
State aggregation of precinct-level data appears to be here: ftp://ftpgis1.tlc.state.tx.us/elections

**Comment by dwillis** [comment]
@umbernhard thanks - the precincts there are "Voting Tabulation Districts," which the state defines as:

```The census geographic equivalent of a county election precinct, created for the purpose of relating election data to census data. VTDs can differ from actual election precincts because election precincts do not always follow census geography. During the approximation process that creates VTDs, county election precinct boundaries that do not follow census geography are assigned to the nearest census block boundary.```

That data also does not include votes by type - absentee, early voting, election day, etc - which ideally we'd like to have, so that's why we're not using it as a primary source.

**Comment by umbernhard** [comment]
Ah, I see. Thanks for the response!
